### PR TITLE
Add support for NOTIFY message

### PR DESCRIPTION
**Pull request by mhdawson**
NOTIFY message provides information about voicemail
waiting. add onMwiInfo callback that can be used
to get information from NOTIFY message so that message
waiting info can be handled/displayed.

### CODE REVIEW

**Comment by mhdawson** [comment]
@mscdex just wondering if you will be willing to pull this in/update npm ?

**Comment by mhdawson** [comment]
I have noticed that the code to parse the "mwiConfig" in the acount already seems to be there so I'll take that out and then update the PR once I see if you have any other comments.

**Comment by mhdawson** [comment]
@mscdex is this still active ?

**Comment by mscdex** [comment]
Unfortunately not really. My original use case for this ended up having problems with the addon mostly due to V8's lazy gc and other things causing memory use issues (even after setting the max old space size and such). That forced me to create a smaller, more limited addon just for the project's needs.

**Comment by mhdawson** [comment]
In that case maybe I'll fork and maintain for my use.

**Pull request closed without merging**
